### ISSUE TITLE
New & Updated Image

### ISSUE THREAD

**Issue by halsteadb** [yourhead/faqmaker#10]
Don't seem to be displayed on page (preview or publish) and need alt tag please.

RW6.3.8

**Comment by yourhead** [comment]
These seem to work in my tests.  Can you provide more detail on how to reproduce this bug.

I'm afraid changing the content generation (adding alt tags) is out of the question for this round of updates.  However you can certainly file a separate bug(feature request) and I'll look into that.

**Comment by halsteadb** [comment]
Publishing issue on my end and thanks for the feedback on the other issues... newbie here so just figuring things out. Will continue to refer to Loghound docs for other info for time being...

**Comment by yourhead** [comment]
marking invalid and closing per user feedback
