### ISSUE TITLE
JSKit - Comment and Rate not functioning

### ISSUE THREAD

**Issue by halsteadb** [yourhead/faqmaker#11]
Don't know if I need to download something in addition to the plugin or if included in plugin but either way, not functioning... [as mentioned in forums](https://forums.realmacsoftware.com/t/faqmaker-v3-0-with-an-all-new-ui/6144)

RW 6.3.8

**Comment by yourhead** [comment]
http://loghound.com/faqmaker/faq/index.html#How_come_the_ratings__comments_

or you can look at the FAQ on this github repo.  The same info is there too.
https://github.com/yourhead/faqmaker/wiki/FAQ

This is a long standing behavior of FAQMaker.  It would be nice to improve that -- but for now these are maintenance updates that just fix RW7 bugs and move things to YourHead -- with a few UI improvements thrown in for fun.  ;-)
